//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsBakery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodsBakery()
        {
            this.Cart = new HashSet<Cart>();
            this.OrderManager = new HashSet<OrderManager>();
        }
    
        public int Id { get; set; }
        public string NameGoods { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> Weight { get; set; }
        public string CallorieValue { get; set; }
        public int ProviderId { get; set; }
        public int TypeOfGoodsId { get; set; }
        public int AllergensId { get; set; }
        public Nullable<int> OnStock { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Allergens Allergens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Cart { get; set; }
        public virtual Category Category { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual TypeOfGoods TypeOfGoods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderManager> OrderManager { get; set; }
    }
}
