//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerOrder
    {
        public int IdTablOrd { get; set; }
        public int IdUser { get; set; }
        public int IdOrder { get; set; }
        public System.DateTime DateTimeOrder { get; set; }
        public int Status { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Users Users { get; set; }
    }
}
