//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderManager
    {
        public int Id { get; set; }
        public int IdOrder { get; set; }
        public int IdGoods { get; set; }
    
        public virtual GoodsBakery GoodsBakery { get; set; }
        public virtual Order Order { get; set; }
    }
}
